[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tools.isort]
line_length = 88
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
